-- =========================
-- 02_create_views.sql
-- Create analytical views for Power BI
-- =========================

USE DATABASE FLEET_ANALYTICS;
USE SCHEMA PUBLIC;

-- Monthly service trend
CREATE OR REPLACE VIEW VW_MONTHLY_TREND AS
SELECT SERVICE_MONTH, COUNT(*) AS TOTAL_SERVICES
FROM SERVICE_EVENTS
GROUP BY SERVICE_MONTH;

-- High-risk assets (most serviced)
CREATE OR REPLACE VIEW VW_HIGH_RISK_ASSETS AS
SELECT ASSET_ID, COUNT(*) AS SERVICE_COUNT
FROM SERVICE_EVENTS
GROUP BY ASSET_ID;

-- Department-wise service trend
CREATE OR REPLACE VIEW VW_DEPARTMENT_TREND AS
SELECT DEPARTMENT, COUNT(*) AS TOTAL_SERVICES
FROM SERVICE_EVENTS
GROUP BY DEPARTMENT;

-- Cost by Department 
CREATE OR REPLACE VIEW VW_COST_BY_DEPARTMENT AS
SELECT
  DEPARTMENT,
  SUM(COALESCE(TOTAL_COST, 0)) AS TOTAL_COST,
  AVG(COALESCE(TOTAL_COST, 0)) AS AVG_COST_PER_SERVICE,
  COUNT(*) AS TOTAL_SERVICES
FROM SERVICE_EVENTS
GROUP BY DEPARTMENT
ORDER BY TOTAL_COST DESC;